### ISSUE TITLE
COHD service returning error

### ISSUE THREAD

**Issue by PhillipsOwen** [WengLab-InformaticsResearch/cohd_api#33]
COHD is returning the error "COHD TRAPI requires at least one node to have an ID" for the trapi v1.1 included here.

[COHD_query.json.txt](https://github.com/WengLab-InformaticsResearch/cohd_api/files/6609969/COHD_query.json.txt)

**Comment by CaseyTa** [comment]
@PhillipsOwen, I just tested this, and the query is working now*. We likely had a previous bug that we already fixed. 

* I made a minor modification to the query to remove constraints from the query nodes. The constraints in your query were set to null, which COHD should ignore, but COHD currently returns an error saying we don't support constraints. I'll create a separate issue on this.

**Comment by PhillipsOwen** [comment]
the query returns data. but it seems that it is not TRAPI compliant. 

(type=value_error.extra)\nmessage -> knowledge_graph -> edges -> ke000150 -> attributes -> 12 -> description\n  extra fields not permitted (type=value_error.extra)'}
ERROR:strider.fetcher:{'message': 'Received non-TRAPI compliant response from KP', 'response': {'datetime': '2021-06-24 15:48:43', 'description': 'COHD returned 292 results.'
...

"descrption" seems to be the offender. 

here is an example what it is complaining about:
                "attributes": [
                  {
                    "attribute_source": "COHD",
                    "attribute_type_id": "biolink:p_value",
                    "description": "Chi-square p-value, unadjusted. http://cohd.io/about.html",
                    "original_attribute_name": "p-value",
                    "value": 0,
                    "value_type_id": "EDAM:data_1669",
                    "value_url": "http://edamontology.org/data_1669"
                  },
                  
valid columns are:
    attribute_type_id: CURIE = Field(..., title="type")
    value: Any = Field(..., title="value")
    value_type_id: Optional[CURIE] = Field(None, title="value_type_id")
    original_attribute_name: Optional[str] = Field(None, nullable=True)
    value_url: Optional[str] = Field(None, nullable=True)
    attribute_source: Optional[str] = Field(None, nullable=True)

**Comment by CaseyTa** [comment]
@PhillipsOwen I'm seeing `description` as a property defined here: 
https://github.com/NCATSTranslator/ReasonerAPI/blob/42a9d073a92d7aaba0ddf080e461d2da088003fc/TranslatorReasonerAPI.yaml#L604

**Comment by PhillipsOwen** [comment]
hrmmm. could this be a case of when spec doesnt meet real world?

i am seeing this in the trapi 1.1.2 code for Attribute.

https://github.com/TranslatorSRI/reasoner-pydantic/blob/v1.1.2/reasoner_pydantic/shared.py
